import React from 'react';
import { Terminal } from 'lucide-react';

const SecuritySummary = ({ summary }) => {
  return (
    <div className="glass-panel" style={{
      background: 'var(--glass-surface)',
      border: '1px solid var(--border-color)',
      borderRadius: 'var(--border-radius)',
      padding: '20px',
      flex: 3,
      minWidth: '300px',
      display: 'flex',
      flexDirection: 'column',
      gap: '12px'
    }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
        <Terminal size={14} style={{ color: 'var(--primary)' }} />
        <span style={{ fontSize: '0.7rem', fontWeight: 'bold', color: 'var(--text-secondary)', letterSpacing: '0.08em' }}>
          SECURITY SUMMARY
        </span>
      </div>
      <p style={{
        fontSize: '0.875rem',
        color: 'var(--text-primary)',
        lineHeight: '1.6',
        fontWeight: '500'
      }}>
        {summary || 'No overall security summary generated by the supervisory analytics engine.'}
      </p>
    </div>
  );
};

export default SecuritySummary;
