import React, { useEffect } from 'react';
import { Link } from 'react-router-dom';
import { Pause, Play, RefreshCw, ShieldAlert } from 'lucide-react';
import LiveIndicator from '../components/common/LiveIndicator';
import EmptyState from '../components/common/EmptyState';
import DashboardSkeleton from '../components/dashboard/DashboardSkeleton';
import AssessmentHeader from '../components/assessment/AssessmentHeader';
import AssessmentStats from '../components/assessment/AssessmentStats';
import AssessmentPriority from '../components/assessment/AssessmentPriority';
import AssessmentSummary from '../components/assessment/AssessmentSummary';
import AssessmentFindings from '../components/assessment/AssessmentFindings';
import AssessmentEvidence from '../components/assessment/AssessmentEvidence';
import { useSupervisoryAssessment } from '../hooks/useSupervisoryAssessment';

const SupervisoryAssessment = ({ setApiStatus, setLastUpdated }) => { const { data, loading, status, error, lastUpdated, autoRefresh, setAutoRefresh, refresh } = useSupervisoryAssessment(); useEffect(() => { setApiStatus?.(status); if (lastUpdated) setLastUpdated?.(lastUpdated); }, [status, lastUpdated, setApiStatus, setLastUpdated]); const assessment = data?.assessment; if (loading && !data) return <DashboardSkeleton />; if (error && !data) return <div style={{ textAlign: 'center', padding: '15vh 20px' }}><ShieldAlert size={44} color="var(--danger)" /><h2 style={{ margin: '16px 0 8px' }}>SUPERVISORY ASSESSMENT UNAVAILABLE</h2><p style={{ color: 'var(--text-secondary)', marginBottom: 20 }}>Unable to retrieve the current supervisory assessment.</p><button onClick={refresh} style={{ background: 'var(--primary)', color: 'white', border: 0, padding: '10px 16px', borderRadius: 6, cursor: 'pointer' }}>Retry</button></div>; if (!assessment) return <EmptyState title="ASSESSMENT UNAVAILABLE" message="No supervisory assessment is currently available." />; return <div style={{ display: 'flex', flexDirection: 'column', gap: 22 }}><header style={{ display: 'flex', justifyContent: 'space-between', gap: 18, flexWrap: 'wrap', alignItems: 'start' }}><div><h1 style={{ fontSize: '1.75rem', marginBottom: 5 }}>SUPERVISORY ASSESSMENT</h1><p style={{ color: 'var(--text-secondary)', fontSize: '0.875rem' }}>Overall cybersecurity posture and supervisory assessment</p></div><div style={{ display: 'flex', alignItems: 'center', gap: 14, flexWrap: 'wrap' }}><LiveIndicator status={status} /><span style={{ color: 'var(--text-muted)', fontSize: '0.75rem', fontFamily: 'var(--font-mono)' }}>Last updated: {lastUpdated || '--'}</span><button onClick={() => setAutoRefresh(!autoRefresh)} title="Toggle auto refresh" style={{ background: 'var(--bg-dark)', border: '1px solid var(--border-color)', color: 'var(--text-primary)', padding: 8, cursor: 'pointer' }}>{autoRefresh ? <Play size={14} /> : <Pause size={14} />}</button><button onClick={refresh} title="Refresh assessment" style={{ background: 'var(--bg-dark)', border: '1px solid var(--border-color)', color: 'var(--text-primary)', padding: 8, cursor: 'pointer' }}><RefreshCw size={14} className={loading ? 'spin-animation' : ''} /></button></div></header><AssessmentHeader /><AssessmentStats assessment={assessment} /><AssessmentPriority priority={assessment.priority} /><AssessmentSummary summary={assessment.summary} /><AssessmentFindings findings={data.findings || []} /><AssessmentEvidence evidence={data.evidence || []} /><nav style={{ display: 'flex', flexWrap: 'wrap', gap: 16, padding: '4px 0 12px' }}><Link to="/findings" style={{ color: 'var(--primary)' }}>View Findings →</Link><Link to="/risk" style={{ color: 'var(--primary)' }}>View Risk →</Link><Link to="/attention" style={{ color: 'var(--primary)' }}>View Attention →</Link><Link to="/resilience" style={{ color: 'var(--primary)' }}>View Resilience →</Link></nav></div>; };
export default SupervisoryAssessment;
