import React, { useEffect } from 'react';
import { ExternalLink, RefreshCw, ShieldAlert } from 'lucide-react';
import LiveIndicator from '../components/common/LiveIndicator';
import DashboardSkeleton from '../components/dashboard/DashboardSkeleton';
import { API_BASE_URL } from '../api/api';
import { useSystemHealth } from '../hooks/useSystemHealth';

const SystemHealth = ({ setApiStatus, setLastUpdated }) => {
  const { services, loading, checking, lastChecked, lastSuccess, autoRefresh, setAutoRefresh, healthStatus, apiBaseUrl, checkNow } = useSystemHealth();
  useEffect(() => { setApiStatus?.(healthStatus === 'CONNECTED' ? 'LIVE' : healthStatus === 'CONNECTING' ? 'CONNECTING' : 'OFFLINE'); if (lastSuccess) setLastUpdated?.(lastSuccess); }, [healthStatus, lastSuccess, setApiStatus, setLastUpdated]);
  const connected = healthStatus === 'CONNECTED';
  const documentationUrl = API_BASE_URL ? `${API_BASE_URL}/docs` : '';
  if (loading && !services.length) return <DashboardSkeleton />;
  return <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
    <header style={{ display: 'flex', justifyContent: 'space-between', gap: 16, alignItems: 'flex-start', flexWrap: 'wrap' }}><div><div style={{ display: 'flex', alignItems: 'center', gap: 10 }}><h1>SYSTEM HEALTH</h1><LiveIndicator status={healthStatus === 'CONNECTED' ? 'LIVE' : healthStatus === 'CONNECTING' ? 'CONNECTING' : 'OFFLINE'} /></div><p style={{ color: 'var(--text-secondary)' }}>SAT-SA frontend and backend connectivity</p></div><div style={{ display: 'flex', alignItems: 'center', gap: 12, color: 'var(--text-muted)', fontSize: '0.78rem' }}><span>Last checked: {lastChecked || '--'}</span><button onClick={checkNow} disabled={checking}><RefreshCw size={15} /> {checking ? 'Checking...' : 'Check Now'}</button><label><input type="checkbox" checked={autoRefresh} onChange={(event) => setAutoRefresh(event.target.checked)} /> Auto Refresh</label></div></header>
    {healthStatus === 'OFFLINE' && <div style={{ padding: 14, border: '1px solid var(--danger)', color: 'var(--danger)', background: 'rgba(239,68,68,.08)' }}><strong>BACKEND OFFLINE</strong><div>The SAT-SA FastAPI backend could not be reached.</div><div>Last successful communication: {lastSuccess || '--'}</div></div>}
    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(190px, 1fr))', gap: 14 }}>{[['BACKEND', healthStatus], ['API STATUS', services.length ? `${services.filter((service) => service.status === 'OK').length}/${services.length} OK` : 'N/A'], ['LAST UPDATE', lastSuccess || '--']].map(([label, value]) => <section key={label} style={{ background: 'var(--bg-dark)', border: '1px solid var(--border-color)', borderRadius: 'var(--border-radius)', padding: 18 }}><div style={{ color: 'var(--text-muted)', fontSize: '0.68rem', fontWeight: 700 }}>{label}</div><div style={{ color: connected ? 'var(--success)' : 'var(--text-primary)', fontSize: '1.35rem', fontWeight: 700, marginTop: 9, wordBreak: 'break-word' }}>{value}</div></section>)}</div>
    <section style={{ background: 'var(--bg-dark)', border: '1px solid var(--border-color)', borderRadius: 'var(--border-radius)', padding: 20, overflowX: 'auto' }}><h2 style={{ fontSize: '0.95rem', marginBottom: 14 }}>API SERVICES</h2><table style={{ width: '100%', minWidth: 650, borderCollapse: 'collapse', fontSize: '0.82rem' }}><thead><tr style={{ color: 'var(--text-muted)', textAlign: 'left', borderBottom: '1px solid var(--border-color)' }}><th style={{ padding: 10 }}>Endpoint</th><th style={{ padding: 10 }}>Status</th><th style={{ padding: 10 }}>HTTP</th><th style={{ padding: 10 }}>Response Time</th><th style={{ padding: 10 }}>Last Checked</th></tr></thead><tbody>{services.map((service) => <tr key={service.path} style={{ borderBottom: '1px solid rgba(255,255,255,.05)' }}><td style={{ padding: 10, fontFamily: 'var(--font-mono)' }}>{service.path}</td><td style={{ padding: 10, color: service.status === 'OK' ? 'var(--success)' : 'var(--danger)' }}>● {service.status}</td><td style={{ padding: 10 }}>{service.httpStatus || 'N/A'}</td><td style={{ padding: 10 }}>{service.responseTime !== undefined ? `${service.responseTime} ms` : 'N/A'}</td><td style={{ padding: 10 }}>{service.checkedAt}</td></tr>)}</tbody></table></section>
    <section style={{ background: 'var(--bg-dark)', border: '1px solid var(--border-color)', borderRadius: 'var(--border-radius)', padding: 20 }}><h2 style={{ fontSize: '0.95rem', marginBottom: 14 }}>CONNECTION INFORMATION</h2><div style={{ display: 'grid', gap: 10, color: 'var(--text-secondary)', fontSize: '0.82rem' }}><div>Backend: <strong style={{ color: 'var(--text-primary)' }}>{healthStatus}</strong></div><div>Base URL: <strong style={{ color: 'var(--text-primary)', wordBreak: 'break-all' }}>{apiBaseUrl || 'Not configured'}</strong></div><div>Auto Refresh: <strong style={{ color: 'var(--text-primary)' }}>{autoRefresh ? 'ON' : 'OFF'}</strong></div></div>{documentationUrl && <a href={documentationUrl} target="_blank" rel="noreferrer" style={{ display: 'inline-flex', gap: 7, alignItems: 'center', marginTop: 16 }}>OPEN API DOCUMENTATION <ExternalLink size={14} /></a>}</section>
    {!services.length && !loading && <div style={{ color: 'var(--danger)' }}><ShieldAlert size={18} /> No API checks completed.</div>}
  </div>;
};

export default SystemHealth;